// api/generate.js
import { GoogleGenerativeAI } from "@google/generative-ai";

// === 1. ТВОРЧЕСКАЯ ИНСТРУКЦИЯ (ДУША) ===
const SYSTEM_INSTRUCTION = `
### ROLE & OBJECTIVE
You translate my thoughts into English LinkedIn posts. Your main goal is clarity and structure without changing my voice. This should feel like I’m speaking, just clearer and more readable.

### LANGUAGE & TONE RULES
- Use simple, conversational English.
- Natural rhythm, slightly informal.
- NO corporate language.
- NO motivational clichés.
- Write like a real person explaining something out loud to a friend.

### FIDELITY TO MY WORDS
- Stay as close as possible to my original wording and intent.
- Do NOT replace my ideas with “better” ones.
`;

const REGENERATE_ANGLES = [
  "Focus heavily on the emotion and personal struggle.",
  "Make it punchy, direct, and slightly contrarian.",
  "Use a storytelling approach: start with a specific moment in time.",
  "Focus on the 'Lesson Learned' aspect, be very practical.",
  "Highlight the contrast between expectation vs reality."
];

const VISUAL_ANGLES = ["Provocative & Bold", "Minimalist & Mysterious", "Direct & Value-driven", "Emotional & Personal"];

export default async function handler(request, response) {
  // Настройка CORS заголовков
  response.setHeader('Access-Control-Allow-Origin', '*');
  response.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  response.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (request.method === 'OPTIONS') return response.status(200).end();
  
  if (request.method !== 'POST') {
    return response.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) return response.status(500).json({ error: "API Key missing" });

    const genAI = new GoogleGenerativeAI(apiKey);
    const { action, rawInput, length, field } = request.body;

    // === 2. ТЕХНИЧЕСКИЙ КОНВЕРТ (ТЕЛО) ===
    let userPrompt = "";
    
    // Техническая инструкция по формату JSON
    const jsonFormatInstruction = `
    CRITICAL TECHNICAL REQUIREMENT:
    Return ONLY a raw JSON object (no markdown, no code blocks) with this structure:
    {
      "postText": "The creative output text...",
      "headline": "A short engaging headline (max 7 words)",
      "subHeadline": "A short context line"
    }`;

    if (action === 'generatePost') {
        const lengthText = length === 'Short' ? "Short & Punchy" : "Thoughtful Storytelling";
        userPrompt = `
        TASK: Write a LinkedIn post based on the INPUT below.
        STYLE: ${lengthText}
        INPUT: "${rawInput}"
        
        ${jsonFormatInstruction}
        `;
    } else if (action === 'regenerateText') {
        const angle = REGENERATE_ANGLES[Math.floor(Math.random() * REGENERATE_ANGLES.length)];
        userPrompt = `
        TASK: Rewrite this post text.
        NEW ANGLE: ${angle}
        INPUT POST: "${rawInput}"
        
        RETURN JSON: { "postText": "New text here..." }
        `;
    } else if (action === 'regenerateVisualField') {
         const angle = VISUAL_ANGLES[Math.floor(Math.random() * VISUAL_ANGLES.length)];
         userPrompt = `
         TASK: Generate a ${field}.
         STYLE: ${angle}
         CONTEXT: "${rawInput}"
         
         RETURN JSON: { "text": "New headline/subheadline..." }
         `;
    } else {
         // Защита от пустого экшена
         userPrompt = `Fix this text: "${rawInput}"`;
    }

    // Используем стабильную модель 2.5 Flash
    const model = genAI.getGenerativeModel({ 
        model: "gemini-2.5-flash", 
        systemInstruction: SYSTEM_INSTRUCTION 
    });

    const result = await model.generateContent(userPrompt);
    const text = result.response.text();
    const cleanText = text.replace(/```json/g, '').replace(/```/g, '').trim();

    try {
        const jsonResponse = JSON.parse(cleanText);
        
        // Страховка от пустых заголовков
        if (action === 'generatePost') {
            if (!jsonResponse.headline) jsonResponse.headline = "New Post";
            if (!jsonResponse.subHeadline) jsonResponse.subHeadline = "Generated by AI";
        }
        
        return response.status(200).json(jsonResponse);

    } catch (e) {
        console.error("JSON Parse Error:", e);
        // Аварийный ответ
        return response.status(200).json({ 
            postText: cleanText, 
            headline: "Format Error", 
            subHeadline: "Please try again" 
        });
    }

  } catch (error) {
    console.error("Server Error:", error);
    return response.status(500).json({ error: error.message });
  }
}
